### ISSUE TITLE
Fetch multiple api data in the MainActivity.

### ISSUE THREAD

**Issue by CC-LU** [RohitSurwase/AAC-MVI-Architecture#4]
If I have to fetch data from three diffrent api in MainActivity.
Could I define three [State/Effect] in this architecture?
Because I need to update UI loading separately.
thx

**Comment by RohitSurwase** [comment]
If you wish to fetch from multiple sources then I will suggest you to have multiple **FetchStatus** in the same **ViewState**.

So it would be like:
`data class MainViewState(val fetchStatusSourceOne: FetchStatus, val fetchStatusSourceTwo: FetchStatus, val fetchStatusSourceThree: FetchStatus, val newsList: List<NewsItem>)`

Later, you can manage these properties based on your business logic.

Please let me know if you have any doubts.

**Comment by tcbnampt** [comment]
Hi @RohitSurwase, as your answer above I have a question for u. 
Do u mean : 
`data class MainViewState(val fetchStatusSourceOne: FetchStatus, val fetchStatusSourceTwo: FetchStatus, val fetchStatusSourceThree: FetchStatus, val newsList1: List<NewsItem1>, val newsList2: List<NewsItem2>, val newsList3: List<NewsItem3>)`

Because when fragment re-create, I want my LiveData save old response. 
As your code above, I have to call api to get data again because u have only one newList item.


Please help understand it clearly. Thanks so much
